### ISSUE TITLE
Multiple declarative shadow roots inside a single host

### ISSUE THREAD

**Issue by rictic** [mfreed7/declarative-shadow-dom#4] opened 2020-03-10 04:26 UTC
What is the desired behavior in this case?

IMO the simplest option, both to understand and to polyfill, is to use the first `<template shadowroot>`, and to simply remove subsequent ones from the DOM. This interpretation _seems_ to be compatible with the algorithm specified in the README, though I'm not super confident of that.

What I'm seeing in the current implementation, with Chrome 82.0.4081 run with `--enable-blink-features=DeclarativeShadowDOM` is that the _last_ `<template shadowroot>` is used, rather than the first.

i.e. this HTML:

```html
  <test-log label="A">
    <template shadowroot="open">
      <test-log label="B"></test-log>
    </template>
    <template shadowroot="open">
      <test-log label="C"></test-log>
    </template>
  </test-log>
```

Renders A and C, but never B. Initially I was wondering if B was attached and then replaced with C somehow, but that does not seem to be the case. Using a side-effecty constructor for `<test-log>` I've verified that B is never instantiated.

**Comment by justinfagnani** [comment] 2020-03-10 18:57
I thought the settled on behavior was to use the first and treat the rest like multiple `attachShadow()` calls, except that because we can't throw, an ErrorEvent would be fired.

**Comment by mfreed7** [comment] 2020-04-02 23:30
That's exactly the behavior I was trying to describe in the README, so please let me know how I can improve the description. The idea is that you only get one `shadowroot` so the **first** one wins and any subsequent ones fail, with an ErrorEvent. The only exception, as described in the (recently updated) README is that you get one imperative call to `attachShadow()` which will blow away a declarative shadow root.

As for the code sample in the original post here - I believe I just fixed that bug a few days ago. I'll double check.

**Comment by mfreed7** [comment] 2020-04-03 01:58
...correction to my comment above. I haven't landed the CL to fix the multiple-shadowroot problem yet, but its coming soon.

**Comment by mfreed7** [comment] 2020-04-20 17:30
Big correction to the above. I've finally put together a PR for the spec changes, and based on how that looks, the **final** declarative shadow root will "win" in this case. The issue is that the "attach a shadow root" algorithm needs to be used for both declarative and imperative roots, and it now removes the contents of existing declarative roots that it finds (so that hydration doesn't break in the presence of DSR). I've added more of the details and an example in the explainer, [here](https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md#existing-declarative-shadow-roots). Note that Chromium behavior is currently the opposite of that, but as I implement the spec changes, it'll swing back to "last root wins".

**Comment by mfreed7** [comment] 2021-03-30 00:10
I believe this issue is all set with the latest explainer and implementation.

**Closed by mfreed7** 2021-03-30 00:10 UTC
